package nginx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopherstack/internal/config"
)

const nginxConfigTemplate = `# GopherStack Enterprise - Auto-Generated Nginx Configuration
# DO NOT EDIT THIS FILE MANUALLY - It will be overwritten on reload

worker_processes auto;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Logging
    log_format upstream_stats '$upstream_addr';
    access_log  "{{.LogDir}}/nginx_access.log";
    error_log   "{{.LogDir}}/nginx_error.log";

    # Performance tuning for Windows
    sendfile        off;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100m;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # PHP FastCGI upstream pool (routed via GopherStack Proxy for metrics)
    upstream php_pool {
        server 127.0.0.1:9000;
        keepalive 64;
    }

    server {
        listen {{.NginxPort}};
        server_name localhost;
        root "{{.DocumentRoot}}";
        index index.php index.html index.htm;

        # Static file serving
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # PHP handling
        location ~ \.php$ {
            fastcgi_pass php_pool;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param QUERY_STRING    $query_string;
            fastcgi_param REQUEST_METHOD  $request_method;
            fastcgi_param CONTENT_TYPE    $content_type;
            fastcgi_param CONTENT_LENGTH  $content_length;
            fastcgi_param SCRIPT_NAME     $fastcgi_script_name;
            fastcgi_param REQUEST_URI     $request_uri;
            fastcgi_param DOCUMENT_URI    $document_uri;
            fastcgi_param DOCUMENT_ROOT   $document_root;
            fastcgi_param SERVER_PROTOCOL $server_protocol;
            fastcgi_param GATEWAY_INTERFACE CGI/1.1;
            fastcgi_param SERVER_SOFTWARE GopherStack/1.0;
            fastcgi_param REMOTE_ADDR     $remote_addr;
            fastcgi_param REMOTE_PORT     $remote_port;
            fastcgi_param SERVER_ADDR     $server_addr;
            fastcgi_param SERVER_PORT     $server_port;
            fastcgi_param SERVER_NAME     $server_name;
            fastcgi_param REDIRECT_STATUS 200;

            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_read_timeout 300;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 16 256k;
            fastcgi_busy_buffers_size 256k;
            fastcgi_keep_conn on;
        }

        # Deny access to hidden files
        location ~ /\. {
            deny all;
        }

        # Nginx metrics for Go monitor
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
            access_log off;
        }
    }
}
`

// WorkerEntry represents a single upstream worker for the template
type WorkerEntry struct {
	Port int
}

// TemplateData holds all data needed for the Nginx config template
type TemplateData struct {
	Workers      []WorkerEntry
	NginxPort    int
	DocumentRoot string
	LogDir       string
}

// ConfigGenerator generates Nginx configuration files
type ConfigGenerator struct {
	cfg *config.Config
}

// NewConfigGenerator creates a new config generator
func NewConfigGenerator(cfg *config.Config) *ConfigGenerator {
	return &ConfigGenerator{cfg: cfg}
}

// Generate creates the nginx.conf file at the specified path
func (g *ConfigGenerator) Generate(outputPath string) error {
	// Resolve LogDir relative to Nginx binary directory (prefix -p)
	nginxDir := filepath.Dir(g.cfg.NginxBinaryPath)
	relLogDir, err := filepath.Rel(nginxDir, g.cfg.LogDir)
	if err != nil {
		relLogDir = filepath.ToSlash(g.cfg.LogDir) // Fallback to absolute if Rel fails
	} else {
		relLogDir = filepath.ToSlash(relLogDir)
	}

	// Build template data
	data := TemplateData{
		NginxPort:    g.cfg.NginxPort,
		DocumentRoot: filepath.ToSlash(g.cfg.DocumentRoot),
		LogDir:       relLogDir,
	}

	// Add worker entries
	for _, port := range g.cfg.WorkerPorts() {
		data.Workers = append(data.Workers, WorkerEntry{Port: port})
	}

	// Parse and execute template
	tmpl, err := template.New("nginx.conf").Parse(nginxConfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse nginx config template: %w", err)
	}

	// Ensure output directory exists
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute nginx config template: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(buf.String()), 0644); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	return nil
}
